
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 22 13:46:44 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 44;
  public static final int LTE = 45;
  public static final int CONST = 6;
  public static final int LTEQ = 46;
  public static final int EQUALS = 7;
  public static final int TERNARY = 37;
  public static final int CASE = 31;
  public static final int LPAREN = 17;
  public static final int SEMI = 8;
  public static final int CONTINUE = 26;
  public static final int CHARC = 11;
  public static final int MINUS = 38;
  public static final int RPAREN = 18;
  public static final int AND = 36;
  public static final int NUMC = 10;
  public static final int NEQTO = 42;
  public static final int OR = 35;
  public static final int COMMA = 9;
  public static final int CLASS = 15;
  public static final int INC = 33;
  public static final int DIV = 49;
  public static final int PLUS = 47;
  public static final int IF = 21;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 48;
  public static final int MOD = 50;
  public static final int BREAK = 25;
  public static final int IDENT = 5;
  public static final int VOID = 19;
  public static final int GTE = 43;
  public static final int SWITCH = 24;
  public static final int LSQBRA = 13;
  public static final int COLON = 32;
  public static final int EQTO = 41;
  public static final int BOOLC = 12;
  public static final int LBRACE = 3;
  public static final int ELSE = 30;
  public static final int ENUM = 20;
  public static final int READ = 28;
  public static final int WHILE = 23;
  public static final int RSQBRA = 14;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 16;
  public static final int DEC = 34;
  public static final int PRINT = 29;
  public static final int DO = 22;
}

